name: kmeans-mapreduce
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - matplotlib
  - jupyter
  - hadoop
  - openjdk
  - opencv-python
  - pip:
    - mrjob
    - seaborn